aliases:
  - &setup_environment
    name: Setup environment
    command: |
      echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
      apk add --no-cache --update --upgrade alpine-sdk make bash maven openjdk8 diffutils jq python2 python2-dev py2-pip ruby ruby-dev perl perl-dev wget rsync go nodejs npm unzip automake autoconf libtool
      echo "gem: --no-document" > ~/.gemrc
      gem install bundler io-console
      pip install pipenv==8.3.2
      curl --fail -L http://cpanmin.us/ > /usr/local/bin/cpanm && chmod +x /usr/local/bin/cpanm
      mkdir -p /protobuf
      curl -L https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-all-3.6.1.tar.gz | tar xvz --strip-components=1 -C /protobuf
      cd /protobuf
      ./autogen.sh
      ./configure
      make -j2
      make check
      make install
    when: always

version: 2
jobs:
  c21e: 
    docker:
      - image: alpine:3.8
    working_directory: ~/app
    steps:
      - run: *setup_environment
      - checkout
      - run: cd c21e
      - run: make


workflows:
  version: 2
  release:
    jobs: 
      - c21e
