version: 2
jobs:
  c21e: 
    docker:
      - image: yoant/circleci-node-ruby
    steps:
      - checkout
      - run: cd c21e
      - run: make


workflows:
  version: 2
  release:
    jobs: 
      - c21e
